# Generated by Django 4.2.3 on 2025-04-05 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_remove_payment_paid_at_remove_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='owner',
            field=models.ForeignKey(default='mkataw', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
