# Generated by Django 4.2.3 on 2025-04-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_stadium_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
    ]
