# Generated by Django 4.2.3 on 2025-04-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_apiurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='location',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
